title: pniedzielski
email: patrick@pniedzielski.net
description: >-
  I am a linguist at MIT.
baseurl: /
url: https://pniedzielski.net
github_username: pniedzielski
permalink: /:categories/:year/:slug

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
incremental: true
strict_front_matter: true

# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
